name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull docker image
      run: sudo docker pull aishitdharwal/ai-projects-track:latest
    - name: Delete old container, if exists
      run: sudo docker rm -f cicd-project || true
    - name: Run latest container
      run: sudo docker run --name cicd-project -p 8000:8000 -d aishitdharwal/ai-projects-track:latest
